---
deployment:
  tasks:
    - export DEPLOYPATH=/home/willpowe/server/
    - export PUBLICPATH=/home/willpowe/server/public/
    - export REPOPATH=/home/willpowe/repositories/will-power/
    - cd $REPOPATH
    - cd back_end
    - npm install
    - cd ..
    - cp -TRv back_end $DEPLOYPATH
    - cd front_end
    - npm install
    - npm run build
    - cp -TRv dist $PUBLICPATH
    - cd $DEPLOYPATH
    - npm run prod
